// Generated from data/car-models.json by scripts/build-vehicle-catalog.mjs — do not edit by hand.

import type { VehicleCatalog } from "./vehicleCatalog";

/** Every make and model the Vehicle pickers offer, in the order the catalogue lists them. */
export const VEHICLE_CATALOG: VehicleCatalog = [
  { make: "Toyota", models: ["Aygo", "Yaris", "Yaris Cross", "Corolla", "Auris", "Avensis", "Camry", "Prius", "C-HR", "RAV4", "Highlander", "Land Cruiser", "Hilux", "Supra", "GR86", "Celica", "MR2", "Starlet", "Verso", "Urban Cruiser", "bZ4X", "Sienna", "Tundra", "Tacoma", "4Runner", "Sequoia", "Corolla Cross", "Crown"] },
  { make: "Volkswagen", models: ["Up!", "Polo", "Golf", "Passat", "Arteon", "Jetta", "Bora", "Lupo", "Fox", "Beetle", "Scirocco", "Eos", "Phaeton", "Touran", "Sharan", "Caddy", "T-Roc", "T-Cross", "Tiguan", "Touareg", "Taigo", "Amarok", "Transporter", "Multivan", "Crafter", "ID.3", "ID.4", "ID.5", "ID.7", "ID.Buzz", "CC", "Atlas"] },
  { make: "Ford", models: ["Ka", "Fiesta", "Focus", "Fusion", "Mondeo", "Escort", "Sierra", "Orion", "Scorpio", "Puma", "EcoSport", "Kuga", "Edge", "Explorer", "Mustang", "Mustang Mach-E", "Galaxy", "S-Max", "C-Max", "B-Max", "Transit", "Transit Connect", "Transit Custom", "Ranger", "F-150", "Bronco", "Maverick", "Capri", "Thunderbird"] },
  { make: "Honda", models: ["Jazz", "Civic", "Accord", "CR-V", "HR-V", "Insight", "Legend", "Prelude", "S2000", "NSX", "Integra", "Stream", "FR-V", "e", "ZR-V", "Pilot", "Odyssey", "Ridgeline", "City", "Fit"] },
  { make: "Nissan", models: ["Micra", "Note", "Almera", "Primera", "Sunny", "Juke", "Qashqai", "X-Trail", "Murano", "Pathfinder", "Patrol", "Navara", "Leaf", "Ariya", "Pulsar", "Tiida", "370Z", "350Z", "GT-R", "Skyline", "Silvia", "Terrano", "Interstar", "NV200", "Townstar", "Altima", "Maxima", "Rogue", "Sentra", "Versa"] },
  { make: "Hyundai", models: ["i10", "i20", "i30", "i40", "Accent", "Elantra", "Sonata", "Getz", "Matrix", "ix20", "ix35", "Kona", "Bayon", "Tucson", "Santa Fe", "Palisade", "Ioniq", "Ioniq 5", "Ioniq 6", "Veloster", "Coupe", "Genesis Coupe", "H-1", "Staria", "Creta", "Venue"] },
  { make: "Kia", models: ["Picanto", "Rio", "Ceed", "Cee'd", "ProCeed", "XCeed", "Cerato", "Optima", "K5", "Stinger", "Soul", "Stonic", "Niro", "Sportage", "Sorento", "Carens", "Venga", "Magentis", "EV6", "EV9", "Telluride", "Seltos", "Carnival", "Sedona"] },
  { make: "Chevrolet", models: ["Spark", "Aveo", "Cruze", "Malibu", "Impala", "Camaro", "Corvette", "Trax", "Captiva", "Equinox", "Blazer", "Tahoe", "Suburban", "Silverado", "Colorado", "Volt", "Bolt", "Orlando", "Lacetti", "Matiz", "Kalos", "Epica", "Nubira", "Trailblazer"] },
  { make: "Mercedes-Benz", models: ["A-Class", "B-Class", "C-Class", "CLA", "CLS", "E-Class", "S-Class", "CLK", "SLK", "SL", "SLC", "AMG GT", "GLA", "GLB", "GLC", "GLE", "GLS", "G-Class", "M-Class", "ML", "GL", "R-Class", "V-Class", "Vito", "Sprinter", "Citan", "X-Class", "EQA", "EQB", "EQC", "EQE", "EQS", "190", "W124", "W123"] },
  { make: "BMW", models: ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "6 Series", "7 Series", "8 Series", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "XM", "Z3", "Z4", "Z8", "M2", "M3", "M4", "M5", "M6", "i3", "i4", "i5", "i7", "i8", "iX", "iX1", "iX3", "E30", "E36", "E46", "E39", "E60"] },
  { make: "Audi", models: ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "80", "90", "100", "200", "Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "TT", "R8", "S3", "S4", "RS3", "RS4", "RS5", "RS6", "RS7", "e-tron", "e-tron GT", "Allroad", "Coupe", "Quattro"] },
  { make: "Renault", models: ["Twingo", "Clio", "Modus", "Megane", "Scenic", "Grand Scenic", "Laguna", "Talisman", "Fluence", "Kangoo", "Captur", "Kadjar", "Koleos", "Arkana", "Austral", "Espace", "Symbol", "Thalia", "Zoe", "Twizy", "Trafic", "Master", "R4", "R5", "R19", "R21", "Safrane", "Avantime", "Vel Satis", "Wind"] },
  { make: "Peugeot", models: ["106", "107", "108", "205", "206", "207", "208", "301", "306", "307", "308", "309", "405", "406", "407", "408", "508", "605", "607", "806", "807", "1007", "2008", "3008", "4007", "4008", "5008", "Rifter", "Partner", "Expert", "Boxer", "Bipper", "RCZ", "iOn", "Traveller"] },
  { make: "Citroën", models: ["C1", "C2", "C3", "C3 Aircross", "C4", "C4 Cactus", "C4 Picasso", "C5", "C5 Aircross", "C6", "C8", "C-Elysée", "C-Zero", "Saxo", "Xsara", "Xsara Picasso", "Xantia", "XM", "ZX", "AX", "BX", "DS3", "DS4", "DS5", "Berlingo", "Nemo", "Jumpy", "Jumper", "SpaceTourer", "2CV", "Ami"] },
  { make: "Fiat", models: ["500", "500L", "500X", "Panda", "Punto", "Grande Punto", "Tipo", "Bravo", "Brava", "Stilo", "Croma", "Linea", "Uno", "Seicento", "Cinquecento", "Marea", "Multipla", "Doblo", "Fiorino", "Qubo", "Scudo", "Ducato", "Talento", "Fullback", "Sedici", "Barchetta", "Coupe", "Freemont", "124 Spider", "Ulysse", "Idea"] },
  { make: "Opel", models: ["Adam", "Karl", "Corsa", "Astra", "Vectra", "Insignia", "Omega", "Kadett", "Ascona", "Manta", "Calibra", "Tigra", "Meriva", "Zafira", "Agila", "Signum", "Antara", "Crossland", "Grandland", "Mokka", "Frontera", "Combo", "Vivaro", "Movano", "Speedster", "GT", "Rocks-e"] },
  { make: "Škoda", models: ["Citigo", "Fabia", "Rapid", "Scala", "Octavia", "Superb", "Felicia", "Favorit", "Forman", "Roomster", "Yeti", "Kamiq", "Karoq", "Kodiaq", "Kushaq", "Enyaq", "Elroq", "Epiq", "Fabia Combi", "Praktik"] },
  { make: "SEAT", models: ["Marbella", "Ibiza", "Arosa", "Cordoba", "Leon", "Toledo", "Altea", "Alhambra", "Exeo", "Mii", "Ateca", "Arona", "Tarraco", "Inca", "Ronda", "Malaga"] },
  { make: "Cupra", models: ["Formentor", "Born", "Leon", "Ateca", "Tavascan", "Terramar", "Raval"] },
  { make: "Dacia", models: ["Sandero", "Logan", "Duster", "Lodgy", "Dokker", "Spring", "Jogger", "Bigster", "Solenza", "Nova", "1310", "Pickup"] },
  { make: "Suzuki", models: ["Alto", "Celerio", "Splash", "Swift", "Baleno", "Ignis", "Wagon R+", "Liana", "SX4", "SX4 S-Cross", "Vitara", "Grand Vitara", "Jimny", "Kizashi", "Samurai", "Swace", "Across", "S-Cross", "Fronx", "eVitara"] },
  { make: "Mazda", models: ["2", "3", "5", "6", "121", "323", "626", "MX-3", "MX-5", "MX-30", "RX-7", "RX-8", "CX-3", "CX-30", "CX-5", "CX-60", "CX-7", "CX-9", "CX-80", "Premacy", "Tribute", "BT-50", "Xedos"] },
  { make: "Mitsubishi", models: ["Space Star", "Colt", "Lancer", "Lancer Evolution", "Galant", "Carisma", "Eclipse", "Eclipse Cross", "ASX", "Outlander", "Pajero", "Pajero Sport", "L200", "Grandis", "Sigma", "3000GT", "i-MiEV", "Mirage", "Attrage"] },
  { make: "Subaru", models: ["Justy", "Impreza", "WRX", "WRX STI", "Legacy", "Outback", "Forester", "XV", "Crosstrek", "Tribeca", "BRZ", "Levorg", "Solterra", "Ascent", "SVX", "Baja"] },
  { make: "Volvo", models: ["240", "340", "440", "460", "480", "740", "850", "940", "960", "S40", "S60", "S70", "S80", "S90", "V40", "V50", "V60", "V70", "V90", "C30", "C70", "XC40", "XC60", "XC70", "XC90", "EX30", "EX90", "EX40", "EC40", "ES90"] },
  { make: "Land Rover", models: ["Defender", "Discovery", "Discovery Sport", "Freelander", "Range Rover", "Range Rover Sport", "Range Rover Evoque", "Range Rover Velar"] },
  { make: "Jaguar", models: ["XE", "XF", "XJ", "XK", "X-Type", "S-Type", "F-Type", "E-Pace", "F-Pace", "I-Pace", "E-Type", "Mark 2", "XJS"] },
  { make: "MINI", models: ["Cooper", "One", "Cooper S", "John Cooper Works", "Clubman", "Countryman", "Paceman", "Coupe", "Roadster", "Cabrio", "Aceman", "Electric"] },
  { make: "Porsche", models: ["911", "718 Boxster", "718 Cayman", "Boxster", "Cayman", "924", "928", "944", "968", "959", "Carrera GT", "918 Spyder", "Panamera", "Cayenne", "Macan", "Taycan", "356"] },
  { make: "Lexus", models: ["CT", "IS", "ES", "GS", "LS", "RC", "LC", "UX", "NX", "RX", "GX", "LX", "LFA", "SC", "RZ", "LBX", "LM"] },
  { make: "Jeep", models: ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler", "Gladiator", "Commander", "Patriot", "Liberty", "Avenger", "Wagoneer", "Grand Wagoneer", "CJ", "Willys"] },
  { make: "Dodge", models: ["Charger", "Challenger", "Viper", "Durango", "Journey", "Caliber", "Avenger", "Nitro", "Dart", "Neon", "Ram", "Stratus", "Magnum", "Caravan", "Grand Caravan", "Hornet"] },
  { make: "Chrysler", models: ["300", "300C", "PT Cruiser", "Sebring", "Crossfire", "Voyager", "Grand Voyager", "Town & Country", "Pacifica", "200", "Neon", "Stratus", "Concorde", "LHS", "Aspen"] },
  { make: "RAM", models: ["1500", "2500", "3500", "ProMaster", "ProMaster City", "Dakota", "TRX", "Rampage"] },
  { make: "GMC", models: ["Sierra", "Canyon", "Yukon", "Acadia", "Terrain", "Savana", "Hummer EV", "Envoy", "Jimmy", "Safari"] },
  { make: "Buick", models: ["Enclave", "Encore", "Envision", "LaCrosse", "Regal", "Verano", "Lucerne", "Century", "Riviera", "LeSabre", "Park Avenue", "Roadmaster"] },
  { make: "Cadillac", models: ["CTS", "ATS", "CT4", "CT5", "CT6", "XTS", "XT4", "XT5", "XT6", "Escalade", "SRX", "STS", "DTS", "Eldorado", "DeVille", "Seville", "Lyriq", "Celestiq", "Optiq", "BLS"] },
  { make: "Lincoln", models: ["Navigator", "Aviator", "Corsair", "Nautilus", "MKZ", "MKX", "MKC", "MKS", "MKT", "Continental", "Town Car", "LS", "Mark VIII"] },
  { make: "Tesla", models: ["Model S", "Model 3", "Model X", "Model Y", "Cybertruck", "Roadster", "Semi"] },
  { make: "Alfa Romeo", models: ["MiTo", "Giulietta", "Giulia", "147", "156", "159", "164", "166", "145", "146", "155", "33", "75", "GT", "GTV", "Spider", "Brera", "4C", "8C", "Stelvio", "Tonale", "Junior"] },
  { make: "Lancia", models: ["Ypsilon", "Delta", "Musa", "Thesis", "Lybra", "Kappa", "Dedra", "Prisma", "Thema", "Phedra", "Voyager", "Flavia", "Fulvia", "Stratos", "037"] },
  { make: "Maserati", models: ["Ghibli", "Quattroporte", "Levante", "Grecale", "GranTurismo", "GranCabrio", "MC20", "Coupe", "Spyder", "3200 GT", "Biturbo", "MCPura", "Merak"] },
  { make: "Ferrari", models: ["296 GTB", "296 GTS", "812 Superfast", "SF90 Stradale", "F8 Tributo", "Roma", "Portofino", "Purosangue", "488", "458 Italia", "California", "F12berlinetta", "FF", "GTC4Lusso", "599 GTB", "612 Scaglietti", "F430", "360 Modena", "F355", "348", "Testarossa", "F40", "F50", "Enzo", "LaFerrari", "12Cilindri", "Daytona SP3", "Amalfi"] },
  { make: "Lamborghini", models: ["Huracán", "Aventador", "Gallardo", "Murciélago", "Diablo", "Countach", "Urus", "Revuelto", "Miura", "Espada", "Jalpa", "Temerario"] },
  { make: "Bentley", models: ["Continental GT", "Flying Spur", "Bentayga", "Mulsanne", "Arnage", "Azure", "Brooklands", "Turbo R", "Bacalar", "Batur"] },
  { make: "Rolls-Royce", models: ["Phantom", "Ghost", "Wraith", "Dawn", "Cullinan", "Spectre", "Silver Shadow", "Silver Spirit", "Silver Seraph", "Corniche"] },
  { make: "Aston Martin", models: ["DB11", "DB12", "DBS", "DBX", "Vantage", "Vanquish", "Rapide", "Valkyrie", "Valhalla", "DB9", "DB7", "V8 Vantage", "Virage", "Lagonda", "Cygnet"] },
  { make: "McLaren", models: ["540C", "570S", "600LT", "650S", "675LT", "720S", "750S", "765LT", "Artura", "GT", "GTS", "MP4-12C", "P1", "Senna", "Speedtail", "Elva", "F1", "Solus GT", "W1"] },
  { make: "Bugatti", models: ["Veyron", "Chiron", "Divo", "Centodieci", "Bolide", "La Voiture Noire", "Mistral", "Tourbillon", "EB110"] },
  { make: "Smart", models: ["Fortwo", "Forfour", "Roadster", "Crossblade", "#1", "#3", "#5"] },
  { make: "Saab", models: ["9-3", "9-5", "9-2X", "9-4X", "9-7X", "900", "9000", "99", "96", "Sonett"] },
  { make: "Lada", models: ["Niva", "Niva Travel", "Niva Legend", "Samara", "110", "111", "112", "Priora", "Kalina", "Granta", "Vesta", "XRAY", "Largus", "2101", "2102", "2103", "2104", "2105", "2106", "2107", "2108", "2109", "21099", "Riva", "Aura", "Iskra"] },
  { make: "UAZ", models: ["Patriot", "Hunter", "469", "452", "Pickup", "Profi", "Simbir"] },
  { make: "Daewoo", models: ["Matiz", "Tico", "Lanos", "Nubira", "Leganza", "Espero", "Nexia", "Racer", "Tacuma", "Kalos", "Evanda", "Lacetti"] },
  { make: "SsangYong", models: ["Korando", "Rexton", "Actyon", "Actyon Sports", "Kyron", "Musso", "Tivoli", "XLV", "Torres", "Rodius", "Musso Grand", "Istana", "Chairman"] },
  { make: "Infiniti", models: ["Q30", "Q50", "Q60", "Q70", "QX30", "QX50", "QX55", "QX60", "QX70", "QX80", "G35", "G37", "FX35", "FX45", "M35", "EX35", "JX35"] },
  { make: "Acura", models: ["ILX", "TLX", "RLX", "RDX", "MDX", "ZDX", "TSX", "TL", "RSX", "NSX", "Integra", "Legend", "CL", "ADX"] },
  { make: "Genesis", models: ["G70", "G80", "G90", "GV60", "GV70", "GV80", "GV90", "Electrified G80", "X Convertible"] },
  { make: "Isuzu", models: ["D-Max", "MU-X", "Trooper", "Rodeo", "Bighorn", "Gemini", "Piazza", "Amigo", "N-Series", "F-Series", "Elf", "Forward"] },
  { make: "Daihatsu", models: ["Cuore", "Charade", "Sirion", "Terios", "Copen", "Materia", "YRV", "Move", "Mira", "Rocky", "Feroza", "Applause", "Gran Move", "Fourtrak", "Hijet", "Cast"] },
  { make: "Datsun", models: ["on-DO", "mi-DO", "GO", "GO+", "Cross", "Redi-GO", "240Z", "280Z", "510", "Sunny", "Bluebird", "Cherry", "Violet"] },
  { make: "Rover", models: ["25", "45", "75", "200", "400", "600", "800", "100", "Metro", "Maestro", "Montego", "SD1", "Streetwise", "CityRover", "Mini"] },
  { make: "MG", models: ["ZS", "HS", "MG3", "MG4", "MG5", "MG6", "Marvel R", "Cyberster", "MGB", "MGF", "TF", "ZR", "ZT", "ZT-T", "Midget", "Maestro", "Montego", "EHS"] },
  { make: "Polestar", models: ["1", "2", "3", "4", "5", "6"] },
  { make: "BYD", models: ["Atto 3", "Dolphin", "Dolphin Surf", "Seal", "Seal U", "Seal 6", "Sealion 7", "Han", "Tang", "Song Plus", "Song L", "Qin Plus", "Yuan Plus", "e6", "Yangwang U8", "Yangwang U9", "Tang EV", "Atto 2", "Shark 6"] },
  { make: "Chery", models: ["Tiggo 4", "Tiggo 7", "Tiggo 8", "Arrizo 5", "Arrizo 6", "QQ", "Fulwin", "Eastar", "Tiggo 9", "Tiggo 3", "Omoda 5", "eQ7", "Exeed TXL", "Exeed VX", "Exeed LX", "Exeed RX"] },
  { make: "Geely", models: ["Emgrand", "Coolray", "Atlas", "Tugella", "Azkarra", "Monjaro", "Okavango", "Geometry C", "Galaxy E5", "Galaxy L7", "Galaxy Starship 7", "Boyue", "Binrui", "Xingyue L", "EX5", "EX2", "CK", "MK", "Vision", "Panda"] },
  { make: "Great Wall", models: ["Wingle 5", "Wingle 7", "Steed", "Hover", "Poer", "Cannon", "Tank 300", "Tank 500", "Voleex C30", "Florid", "Safe", "Deer", "Ora", "Cowry"] },
  { make: "Haval", models: ["H6", "H9", "Jolion", "Dargo", "H2", "H3", "H5", "H7", "F7", "F7x", "M6", "Big Dog", "Raptor", "H6 GT"] },
  { make: "GAC", models: ["Aion S", "Aion Y", "Aion V", "Aion Hyper", "Emkoo", "Empow", "GS3", "GS4", "GS8", "GA4", "GA6", "GN6", "GN8", "GM8", "Trumpchi", "M6", "Hyptec HT", "Hyptec GT"] },
  { make: "Dongfeng", models: ["Aeolus", "Fengon 500", "Fengon 580", "Fengon E5", "Forthing T5", "Forthing T5 EVO", "Rich 6", "Rich 7", "Nammi", "Mengshi", "Voyah Free", "Shine Max", "Box", "S30", "H30 Cross", "AX7", "E70", "A9", "Yixuan"] },
  { make: "NIO", models: ["ES6", "ES7", "ES8", "EC6", "EC7", "ET5", "ET5T", "ET7", "ET9", "ES6 Mk2", "Onvo L60", "Firefly", "EP9"] },
  { make: "XPeng", models: ["G3", "G6", "G9", "P5", "P7", "P7+", "Mona M03", "X9", "G7", "P7i", "G3i", "Mona", "X2"] },
  { make: "Li Auto", models: ["L6", "L7", "L8", "L9", "i6", "i8", "Mega", "One", "i8 Max", "L6 Max"] },
  { make: "Zeekr", models: ["001", "001 FR", "007", "009", "7X", "X", "Mix", "001 Ultra", "007 GT", "8X"] },
  { make: "Lynk & Co", models: ["01", "02", "03", "05", "06", "08", "09", "900", "Z10", "Z20"] },
  { make: "Jetour", models: ["X70", "X70 Plus", "X90", "X95", "Dashing", "Traveller", "T2", "Shanhai T1", "Shanhai T2", "T1", "Ice Cream", "Soueast S07"] },
  { make: "Omoda", models: ["5", "7", "9", "5 EV", "C5", "C7", "E5", "C9", "Omoda 5 GT", "Omoda 7 SHS"] },
  { make: "Jaecoo", models: ["5", "7", "6", "8", "J7", "J6", "7 SHS", "5 EV", "J8", "J5"] },
  { make: "Leapmotor", models: ["T03", "C10", "C11", "C16", "B10", "B05", "C01", "S01", "C10 REEV", "A10", "Lafa5", "Lafa"] },
  { make: "Wuling", models: ["Hongguang MINI EV", "Air EV", "Bingo", "Starlight", "Almaz", "Cortez", "Confero", "Victory", "Sunshine", "Zhengtu", "Yunduo", "Cloud"] },
  { make: "Changan", models: ["CS35 Plus", "CS55 Plus", "CS75 Plus", "CS85", "CS95", "Alsvin", "Eado", "UNI-K", "UNI-V", "UNI-T", "UNI-Z", "Deepal S7", "Deepal SL03", "Avatr 11", "Hunter", "Raeton", "Benni"] },
  { make: "JAC", models: ["J7", "S3", "S4", "S5", "S7", "iEV7", "e-JS1", "T6", "T8", "N-series", "Refine", "Rein", "iEV6E", "JS4", "E-JS4", "Sunray", "Shuailing"] },
  { make: "FAW", models: ["Bestune B70", "Bestune T77", "Bestune T99", "Bestune NAT", "Bestune B50", "Bestune T33", "Jiefang", "Besturn X40", "Pentium", "Xenia", "Oley", "Vita", "Haima"] },
  { make: "Hongqi", models: ["H5", "H7", "H9", "HS5", "HS7", "E-HS9", "E-QM5", "L5", "LS7", "H6", "H9+", "Guoya", "EHS7", "HS3"] },
  { make: "Tata", models: ["Nano", "Indica", "Indigo", "Tiago", "Tigor", "Altroz", "Punch", "Nexon", "Harrier", "Safari", "Sumo", "Sierra", "Curvv", "Avinya", "Xenon", "Aria", "Manza"] },
  { make: "Mahindra", models: ["Scorpio", "XUV300", "XUV500", "XUV700", "Thar", "Bolero", "Marazzo", "KUV100", "Verito", "BE 6e", "XEV 9e", "Scorpio-N", "Xylo", "Pik-Up", "Alturas G4"] },
  { make: "Proton", models: ["Saga", "Persona", "Wira", "Waja", "Gen-2", "Satria", "Exora", "Preve", "Iriz", "X50", "X70", "X90", "Perdana", "Suprima S", "e.MAS 7", "e.MAS 5"] },
  { make: "Perodua", models: ["Myvi", "Axia", "Bezza", "Aruz", "Alza", "Ativa", "Kancil", "Kelisa", "Kenari", "Viva", "Kembara", "Rusa", "Nautica", "Arruz"] },
  { make: "Holden", models: ["Commodore", "Barina", "Cruze", "Astra", "Captiva", "Colorado", "Ute", "Monaro", "Calais", "Statesman", "Torana", "Kingswood", "Crewman", "Trax", "Acadia", "Equinox"] },
  { make: "Lotus", models: ["Elise", "Exige", "Evora", "Emira", "Eletre", "Emeya", "Esprit", "Elan", "Europa", "Seven", "Evija", "Eletre R", "Carlton", "Cortina", "Lotus 3-Eleven"] },
  { make: "Pagani", models: ["Zonda", "Huayra", "Utopia", "Imola", "Codalunga", "Zonda R", "Huayra BC", "Zonda F", "Huayra R", "Huayra Roadster"] },
  { make: "Koenigsegg", models: ["Regera", "Jesko", "Gemera", "CC8S", "CCR", "CCX", "Agera", "One:1", "Agera RS", "CCXR", "Jesko Absolut", "CC850"] },
  { make: "Rimac", models: ["Nevera", "Concept One", "Concept Two", "Nevera R"] },
  { make: "Morgan", models: ["Plus Four", "Plus Six", "Aero 8", "Super 3", "3 Wheeler", "4/4", "Roadster", "Aeromax", "Plus 8", "Aero GT", "EvaGT", "Threewheeler"] },
  { make: "Alpine", models: ["A110", "A110 S", "A110 R", "A290", "A390", "A310", "GTA", "A610", "A108", "V6 GTA", "Renault Alpine"] },
  { make: "DS Automobiles", models: ["DS 3", "DS 3 Crossback", "DS 4", "DS 5", "DS 7", "DS 7 Crossback", "DS 9", "DS N°4", "DS N°8", "DS 3 E-Tense"] },
  { make: "Abarth", models: ["595", "695", "500e", "124 Spider", "Punto Evo", "Grande Punto", "124 Rally", "600e", "850 TC", "1000 TC", "Simca 1150", "Fiat Abarth 500", "Fiat Abarth 695", "Abarth 1000"] },
  { make: "Iveco", models: ["Daily", "Eurocargo", "S-Way", "Stralis", "Trakker", "Massif", "Eurotech", "Eurostar", "eDaily", "Turbostar", "Turbotech", "Powerstar", "Zeta", "Vertis", "Campagnola"] },
  { make: "Maybach", models: ["57", "62", "57 S", "62 S", "Landaulet", "Exelero", "Mercedes-Maybach S-Class", "Mercedes-Maybach GLS", "Mercedes-Maybach EQS SUV", "Mercedes-Maybach SL", "Zeppelin", "Cabriolet", "Maybach 57 Zeppelin", "Maybach 62 Landaulet"] },
  { make: "Pontiac", models: ["Firebird", "Trans Am", "GTO", "Grand Am", "Grand Prix", "Bonneville", "Sunfire", "Vibe", "G6", "G8", "Solstice", "Aztek", "Montana", "Fiero", "Torrent"] },
  { make: "Oldsmobile", models: ["Cutlass", "Alero", "Aurora", "Intrigue", "Bravada", "Silhouette", "88", "98", "Toronado", "442", "Ciera", "Achieva", "Delta 88", "Firenza"] },
  { make: "Plymouth", models: ["Barracuda", "Road Runner", "Duster", "Fury", "Prowler", "Voyager", "Neon", "Breeze", "Acclaim", "Sundance", "Valiant", "Superbird", "GTX", "Belvedere"] },
  { make: "Mercury", models: ["Cougar", "Grand Marquis", "Sable", "Mountaineer", "Milan", "Mariner", "Montego", "Mystique", "Tracer", "Villager", "Capri", "Marauder", "Topaz", "Comet"] },
  { make: "Saturn", models: ["Ion", "S-Series", "L-Series", "Vue", "Aura", "Sky", "Outlook", "Relay", "SC", "SL", "SW", "Astra", "Curve", "Green Line"] },
  { make: "Hummer", models: ["H1", "H2", "H3", "H3T", "EV", "H2 SUT", "HMMWV", "Alpha", "H3 Alpha", "H2 SUT Pickup", "H1 Alpha", "Hummer EV Pickup", "Hummer EV SUV"] },
  { make: "Scion", models: ["tC", "xB", "xD", "xA", "iQ", "FR-S", "iA", "iM", "FR-S Release Series", "xB RS", "tC Release Series", "Scion iQ EV", "Scion FR-S", "Scion xB Release Series"] },
  { make: "Fisker", models: ["Karma", "Ocean", "Pear", "Ronin", "Alaska", "Atlantic", "Spectre", "Rocket", "Ocean Extreme", "Ocean One", "Ocean Sport", "Ocean Ultra"] },
  { make: "Lucid", models: ["Air", "Gravity", "Air Pure", "Air Touring", "Air Grand Touring", "Air Sapphire", "Air Dream Edition", "Gravity Touring", "Gravity Grand Touring", "Gravity Dream Edition"] },
  { make: "Rivian", models: ["R1T", "R1S", "R2", "R3", "R3X", "EDV", "R1T Quad", "R1S Quad", "R1T Adventure", "R1S Adventure", "R1T Launch Edition"] },
  { make: "VinFast", models: ["VF 3", "VF 5", "VF 6", "VF 7", "VF 8", "VF 9", "VF e34", "VF Wild", "VF MPV 7", "Lux A2.0", "Lux SA2.0", "Fadil", "President", "VF 8 Plus", "VF 9 Plus"] },
  { make: "Trabant", models: ["601", "P50", "P60", "1.1", "P70", "Tramp", "Kübel", "Universal", "Limousine", "Kombi", "Hycomat", "nT", "Trabant 500", "Trabant 600"] },
  { make: "Wartburg", models: ["311", "353", "1.3", "312", "313", "Tourist", "Knight", "Trans", "Cabrio", "Sport", "Wartburg 900", "Wartburg 850", "Wartburg 1.3 HT", "Wartburg Kombi"] },
  { make: "Zastava", models: ["101", "128", "750", "Yugo", "Koral", "Florida", "Skala", "10", "Sana", "Cargo", "Poly", "Tempo", "Yugo 45", "Yugo 55", "Yugo 65", "Yugo GV"] },
  { make: "Moskvich", models: ["412", "2140", "2141", "Aleko", "Svyatogor", "Knyaz Vladimir", "Moskvich 3", "Moskvich 6", "Moskvich 8", "Moskvich 3e", "Moskvich 400", "Moskvich 401", "Moskvich 402", "Moskvich 407"] },
  { make: "GAZ", models: ["Volga", "Gazelle", "Gazelle Next", "Sobol", "Valdai", "Siber", "24", "31105", "3110", "Pobeda", "Chaika", "M20", "Volga 3102", "Gazelle Business", "Gazelle Nn", "Gazon Next"] },
  { make: "Tatra", models: ["T87", "T97", "T603", "T613", "T700", "T815", "T813", "T111", "T148", "Phoenix", "Force", "Tatra 11", "Tatra 12", "Tatra 57", "Tatra T2-603", "Tatra 2-603"] },
  { make: "Borgward", models: ["BX5", "BX6", "BX7", "Isabella", "P100", "Hansa", "Arabella", "BXi7", "Borgward 1500", "Borgward 2000", "Goliath", "Lloyd", "Borgward BX5 EV", "Borgward BX6 TS"] },
  { make: "Aiways", models: ["U5", "U6", "U7", "Ei6", "U6 Ion", "Aiways U5 Ion", "Aiways U6 Electric Coupe SUV", "Aiways U7 Ion", "Aiways U5 Launch Edition", "Aiways U6 Ion Coupe"] },
  { make: "ORA", models: ["Funky Cat", "Good Cat", "Ballet Cat", "Lightning Cat", "03", "07", "R1", "iQ", "Punk Cat", "Ora 03", "Ora 07", "Ora Cat", "Ora Good Cat", "Ora Ballet Cat"] },
  { make: "Lifan", models: ["320", "520", "620", "720", "X50", "X60", "X70", "Smily", "Breez", "Solano", "Cebrium", "Myway", "Foison", "Cargo", "Rumion", "Lifan 530"] },
  { make: "Vauxhall", models: ["Corsa", "Astra", "Insignia", "Mokka", "Crossland", "Grandland", "Vivaro", "Combo", "Movano", "Zafira", "Adam", "Viva", "Cascada", "Vectra", "Meriva", "Antara"] },
  { make: "Talbot", models: ["Samba", "Horizon", "Solara", "Sunbeam", "Tagora", "Express", "Rancho", "Alpine", "Talbot 1510", "Talbot 180", "Talbot 2 Litre", "Talbot Lago", "Talbot Matra Murena", "Talbot Simca"] },
  { make: "Simca", models: ["1000", "1100", "1307", "1308", "1501", "Aronde", "Chambord", "Vedette", "Ariane", "Horizon", "Rallye", "Simca 1200S", "Simca 1301", "Simca 1501 Special", "Simca P60"] },
  { make: "Austin", models: ["Mini", "Allegro", "Maestro", "Metro", "Montego", "Princess", "Maxi", "A40", "A35", "Healey", "Seven", "Cambridge", "Westminster", "1100"] },
  { make: "Triumph", models: ["TR3", "TR4", "TR6", "TR7", "TR8", "Spitfire", "GT6", "Stag", "Herald", "Dolomite", "Toledo", "2000", "Vitesse", "Acclaim"] },
  { make: "Ineos", models: ["Grenadier", "Grenadier Quartermaster", "Fusilier", "Grenadier Station Wagon", "Grenadier Trialmaster", "Grenadier Belstaff", "Grenadier Utility Wagon"] },
  { make: "Aixam", models: ["City", "Coupe", "Crossline", "Crossover", "GTO", "Minauto", "Scouty R", "Mega", "Aixam A721", "Aixam A741", "Aixam D-Truck", "Aixam e-City", "Aixam e-Coupe"] },
  { make: "Ligier", models: ["JS50", "JS60", "Myli", "Ambra", "Nova", "X-Too", "Pulse", "Optimax", "Ligier JS2", "Ligier JS3", "Ligier JS11", "Ligier JS P2"] },
  { make: "DeLorean", models: ["DMC-12", "Alpha5", "DMC-12 Restored", "DMC-12 Modern", "DMC-12 Stainless Steel", "DMC-12 Prototype"] },
  { make: "Shelby", models: ["Cobra", "GT350", "GT500", "Super Snake", "GT", "Mustang GT350R", "Series 1", "Daytona Coupe", "Shelby 427 Cobra", "Shelby GT500KR", "Shelby Super Snake", "Shelby F-150"] },
  { make: "Saleen", models: ["S281", "S302", "S7", "S331", "S351", "Mustang S281", "Saleen 1", "Saleen Sportruck", "Saleen Explorer", "Saleen Sport Truck", "Saleen Yellow Label"] },
  { make: "Eagle", models: ["Talon", "Vision", "Summit", "Premier", "Medallion", "Talon TSi", "Eagle 2000GTX", "Eagle Summit Wagon", "Eagle Vision TSi"] },
  { make: "Geo", models: ["Metro", "Prizm", "Storm", "Tracker", "Spectrum", "Geo Metro Convertible", "Geo Prizm GSi", "Geo Storm GSi", "Geo Tracker"] },
  { make: "AMC", models: ["Gremlin", "Pacer", "Javelin", "Eagle", "Hornet", "Matador", "Rambler", "Concord", "Spirit", "AMX", "Ambassador", "Rebel"] },
  { make: "Studebaker", models: ["Avanti", "Champion", "Commander", "President", "Lark", "Hawk", "Golden Hawk", "Silver Hawk", "Speedster", "Gran Turismo Hawk", "Studebaker Champion 2 door"] },
  { make: "Ariel", models: ["Atom", "Nomad", "Ace", "Ariel Atom 4", "Ariel Nomad Tactical", "Ariel Atom 3.5R", "Ariel Hipercar", "Ariel Atom 3S"] },
  { make: "Caterham", models: ["Seven 170", "Seven 270", "Seven 360", "Seven 420", "Seven 620", "Seven 620R", "Seven 485", "Seven 160", "Seven CSR", "Seven Roadsport", "Seven Superlight", "Project V"] },
  { make: "TVR", models: ["Griffith", "Chimaera", "Cerbera", "Tuscan", "Sagaris", "Tamora", "Tasmin", "Vixen", "Grantura", "Taimar", "Chimaera 500", "Cerbera Speed 12"] },
  { make: "Noble", models: ["M12", "M400", "M600", "M15", "M10", "Noble M12 GTO", "Noble M14", "Noble M500", "Noble M12 GTO 3R"] },
  { make: "Spyker", models: ["C8", "C12", "D8", "B6 Venator", "C8 Aileron", "C8 Laviolette", "C8 Double 12", "C8 Preliator", "C8 Spyder T", "C8 Spyder", "C12 Zagato", "C12 La Turbie"] },
  { make: "Venturi", models: ["Fetish", "Atlantique", "America", "Gransport", "Eclectic", "Astrolab", "VBB-3", "Venturi 210", "Venturi 260", "Venturi 300", "Venturi 400 GT", "Venturi Atlantique 300"] },
  { make: "Wiesmann", models: ["MF3", "MF4", "MF5", "GT MF4", "GT MF5", "Roadster MF3", "Roadster MF4", "Roadster MF5", "Project Thunderball", "MF25", "Wiesmann GT", "Wiesmann Roadster"] },
  { make: "Brabus", models: ["Rocket 900", "Rocket 800", "G800", "B63S", "B40", "Brabus 600", "Brabus 850", "Brabus 900", "Brabus 700", "Brabus 500", "Brabus 800 Widestar", "Brabus 900 Rocket"] },
  { make: "Daimler", models: ["SP250", "Double-Six", "Sovereign", "Majestic", "Conquest", "DS420", "Limousine", "Daimler 2.5 V8", "Daimler Super V8", "XJ6 Daimler", "XJ12 Daimler", "Daimler Fifteen"] },
  { make: "Kaiyi", models: ["X3", "X3 Pro", "X7", "E5", "Kaiyi Kunlun", "Kaiyi X3 Pro", "Kaiyi X7", "Kaiyi E5", "Kaiyi Kunlun EV", "Kaiyi Kunlun HEV"] },
  { make: "Seres", models: ["3", "5", "7", "SF5", "E1", "Aito M5", "Aito M7", "Aito M9", "Aito M8", "Seres 3", "Seres 5", "Seres 7"] },
  { make: "Avatr", models: ["11", "12", "07", "06", "Avatr 11", "Avatr 12", "Avatr 07", "Avatr 06", "Avatr 11 Long Range", "Avatr 12 Long Range"] },
  { make: "Voyah", models: ["Free", "Dream", "Passion", "Courage", "Voyah Free", "Voyah Dream", "Voyah Passion", "Voyah Courage", "Voyah Free 318", "Voyah Zhuiguang"] },
  { make: "Maxus", models: ["T60", "T90", "eDeliver 3", "eDeliver 9", "Deliver 9", "Mifa 9", "V80", "G10", "D90", "Euniq 5", "Euniq 6", "Euniq 7"] },
];
